const posts = {
  id: 1,
  body: 'post body',
  createdAt: '05/25/2021',
  username: 'firstUser',
  likeCount: 2,
  likes: ['secondUser', 'thirdUser'],
  commentCount: 1,
  comments: {
    id: 1,
    body: 'comment body',
    username: 'secondUser',
    createdAt: '05/26/2021',
    likeCount: 2,
  },
  id: 2,
  body: 'post body',
  createdAt: '05/24/2021',
  username: 'secondUser',
  likeCount: 2,
  likes: ['firstUser', 'thirdUser'],
  commentCount: 1,
  comments: {
    id: 1,
    body: 'comment body',
    username: 'thirdUser',
    createdAt: '05/24/2021',
    likeCount: 2,
  },
  id: 2,
  body: 'post body',
  createdAt: '05/23/2021',
  username: 'thirdUser',
  likeCount: 2,
  likes: ['firstUser', 'secondUser'],
  commentCount: 1,
  comments: [
    {
      id: 1,
      body: 'comment body',
      username: 'secondUser',
      createdAt: '05/23/2021',
      likeCount: 2,
    },
    {
      id: 2,
      body: 'second comment body',
      username: 'firstUser',
      createdAt: '05/24/2021',
      likeCount: 1,
    },
  ],
};

export default posts;
